### ISSUE TITLE
Requesting Support for Age of Industry Replacement Set v1.3.0

### ISSUE THREAD

**Issue by Grant4455** [mattkimber/timberwolfs_station_ratings#1]
_Hi There!_

Thank you very much for creating this modification; I'm a UK Railfan and have avidly enjoyed your trainsets, road vehicles, and other additions to this wonderful game. After having read the readme in game, I came here to request some support coupling this newGRF into another I enjoy using, AIRS, Age of Industry Replacement Set, a fork of FIRS. 

To clarify, I'm not a developer of that newGRF, nor am I associated. I'm just a player who enjoys AIRS as an alternative to the frankly... Excessive detail of FIRS Steeltown or In and Hot Country, as a midpoint between that, and Temperate or Arctic Basic. The source-code is available publicly at the github I've linked at the bottom of this post.

Please forgive any failure in formatting or procedure on my part. I'm not terribly technical. Regardless of wether or not this is possible, thank you very much for your time.

_Edward_

https://github.com/andybiotic/airs_andysine

**Comment by mattkimber** [comment]
That's all fine! I do want to add more supported industry sets, so will put that on the list.

(Will leave this open for now as a reminder I need to do stuff)

**Comment by mattkimber** [comment]
This should be in now, and available on BaNaNaS
